server:
  port: 8764
#  servlet:
#    context-path: /api

spring:
  application:
    name: service-ribbon
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest

#  zipkin:
#    base-uri: http://localhost:9411 #指定 zipkinServer 的地址。
#  sleuth:
#    sampler:
#      percentage: 1.0 #指定采样请求的百分比（默认为0.1，即10%）


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
